name: Sync images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Sync Docker Images
      env:
        DEST_USERNAME: ${{ secrets.ACR_USERNAME }}
        DEST_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: |
        # 目标注册表的用户名和密码
        DEST_USERNAME=${{ secrets.ACR_USERNAME }}
        DEST_PASSWORD=${{ secrets.ACR_PASSWORD }}

        # 调试信息
        echo "DEST_USERNAME: $DEST_USERNAME"
        echo "DEST_PASSWORD: $DEST_PASSWORD"

        # 检查用户名和密码是否为空
        if [ -z "$DEST_USERNAME" ]; then
          echo "Error: DEST_USERNAME is empty"
          exit 1
        fi

        if [ -z "$DEST_PASSWORD" ]; then
          echo "Error: DEST_PASSWORD is empty"
          exit 1
        fi
        IMAGES=(
          "docker.io/library/aultwarden/server:alpine registry.cn-hangzhou.aliyuncs.com/miaou/vaultwarden:alpine"
        )
        for IMAGE in "${IMAGES[@]}"; do
          SOURCE_IMAGE=$(echo $IMAGE | awk '{print $1}')
          DEST_IMAGE=$(echo $IMAGE | awk '{print $2}')
          echo "Syncing $SOURCE_IMAGE to $DEST_IMAGE"
          echo $DEST_USERNAME
          echo $DEST_PASSWORD | skopeo copy --dest-creds $DEST_USERNAME:$(cat) docker://$SOURCE_IMAGE docker://$DEST_IMAGE
        done