name: Sync images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Sync Docker Images
      env:
        DEST_USERNAME: ${{ secrets.ACR_USERNAME }}
        DEST_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: |
        cd ./image-sync
        bash skopeo-sync.sh images.txt $DEST_USERNAME $DEST_PASSWORD
