name: Sync images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [acr]  # 列出所有需要同步的存储库
        include:
          - repository: acr
            DEST_REPOSITORY: ${{ secrets.ACR_REPOSITORY }}
            DEST_USERNAME: ${{ secrets.ACR_USERNAME }}
            DEST_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Sync Docker Images
      env:
        DEST_REPOSITORY: ${{ matrix.DEST_REPOSITORY }}
        DEST_USERNAME: ${{ matrix.DEST_USERNAME }}
        DEST_PASSWORD: ${{ matrix.DEST_USERNAME }}
      run: cd ./image-sync/ && bash skopeo-sync.sh $DEST_REPOSITORY $DEST_USERNAME $DEST_PASSWORD