name: Sync images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Sync Docker Images
      uses: hhyasdf/image-sync-action@v1.1
      with:
        auth_file: ./image-sync/auth.yaml # The auth information file of registries, optional.
        images_file: ./image-sync/images.yaml # The images file descirbes which images need to sync, always needed.
        version: latest # The version of image-syncer, use the latest version if not specified.
        proc: 6 # The max number of goroutines to sync images, default value is 5.
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }} # For safty consideration, passing registry password by github action secrets is needed.
