name: Sync lobe-chat Repository

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 00:00 运行一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository (lobehub/lobe-chat)
      - name: Checkout source repository
        run: |
          git clone --branch main https://github.com/lobehub/lobe-chat.git source
          cd source
          git checkout main

      # Step 2: Checkout the target repository (QinYangWang/lobe-chat)
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: QinYangWang/lobe-chat
          token: ${{ secrets.PAT }}  # 使用你创建的 PAT
          path: target

      # Step 3: Sync files from source to target
      - name: Sync files
        run: |
          rsync -av --delete source/ target/

      # Step 4: Commit and push changes to the target repository
      - name: Commit and push changes
        run: |
          cd target
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync from lobehub/lobe-chat" || echo "No changes to commit"
          git push origin main
